package eu.dety.burp.joseph.gui;

import javax.swing.*;
import java.awt.*;

/**
 * Help tab with information about this extension
 *
 * @author Dennis Detering
 * @version 1.0
 */
public class UIHelp extends JPanel {

    private JPanel mainPanel;

    public UIHelp() {
        this.add(mainPanel);
        this.setLayout(new GridLayout(0, 1));
        setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.LEFT, 5, 5));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
